name: RykenSlimefunCustomizer
version: '${project.version}'
main: org.lins.mmmjjkx.rykenslimefuncustomizer.RykenSlimefunCustomizer
api-version: '1.18'
depend: [Slimefun, Polymer]
softdepend: [PlaceholderAPI]
authors: [mmmjjkx, hitech0926]
description: An advanced Slimefun customize plugin
libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
commands:
  rykenslimecustomizer:
    aliases: ["rsc"]
    permission: rsc.command
permissions:
  rsc.command:
    default: op