name: RykenSlimefunCustomizer
version: '${project.version}'
main: org.lins.mmmjjkx.rykenslimefuncustomizer.RykenSlimefunCustomizer
api-version: '1.18'
depend: [Slimefun]
softdepend:
  - GuizhanLibPlugin
  - ChestTerminal
  - ColoredEnderChests
  - DyedBackpacks
  - EcoPower
  - ElectricSpawners
  - ExoticGarden
  - ExtraGear
  - ExtraHeads
  - HotbarPets
  - luckyblocks-sf
  - PrivateStorage
  - SlimefunOreChunks
  - SlimyTreeTaps
  - SoulJars
  - CommandOverride
  - EmeraldEnchants2
  - QuickMarket
  - QuickSell
  - RankPrefixPlus
  - LiteXpansion
  - MobCapturer
  - SoundMuffler
  - ExtraTools
  - TranscEndence
  - Liquid
  - SFCalc
  - SlimefunWarfare
  - Slimy-Power-Suits
  - FluffyMachines
  - SlimyRepair
  - InfinityExpansion
  - FoxyMachines
  - GlobalWarming
  - DynaTech
  - GeneticChickengineering
  - HeadLimiter
  - SlimeXpansion
  - Barrels
  - ClayTech
  - FNAmplifications
  - SMG
  - EMC2
  - Simple-Storage
  - AlchimiaVitae
  - SlimeTinker
  - PotionExpansion
  - FlowerPower
  - Galactifun
  - Element-Manipulation
  - CrystamaeHistoria
  - DankTech2
  - Networks
  - VillagerUtil
  - MissileWarfare
  - SensibleToolbox
  - Endrex
  - Bump
  - FinalTech
  - FutureTech
  - bedrocktechnology
  - SlimefunItemExpansion
  - SupplementalServiceableness
  - GuizhanCraft
  - UltimateGenerators-RC27
  - CrispyMachine
  - DimensionTraveler
  - Chocohills
  - draconic
  - EzSFAddon
  - RandomExpansion
  - ExLimus
  - MoneyAndThings
  - VoidHarvesters
  - SlimyBees
  - GeneticManipulation
  - ObsidianExpansion
  - NotEnoughAddons
  - SlimeSec
  - EMCTech
  - RelicsOfCthonia
  - Supreme
  - DyeBench
  - MiniBlocks
  - SlimeHUD
  - SpiritsUnchained
  - Cultivation
  - Gastronomicon
  - SmallSpace
  - BetterGenerator
  - VillagerTrade
  - SlimeFrame
  - AdvancedTech
  - Quaptics
  - FastMachines
authors: [mmmjjkx]
description: An advanced Slimefun customize plugin
libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
commands:
  rykenslimecustomizer:
    aliases: ["rsc"]
    permission: rsc.command.help
permissions:
  rsc.command:
    default: op
    children:
      rsc.command.help: true
      rsc.command.reload: true
      rsc.command.list: true
      rsc.command.reloadPlugin: true
      rsc.command.saveitem: true
      rsc.command.enable: true
      rsc.command.disable: true
      rsc.command.menupreview: true
  rsc.command.help:
    default: op
  rsc.command.reload:
    default: op
  rsc.command.list:
    default: op
  rsc.command.reloadPlugin:
    default: op
  rsc.command.saveitem:
    default: op
  rsc.command.enable:
    default: op
  rsc.command.disable:
    default: op
  rsc.command.menupreview:
    default: op